// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzrgoudfoiwrytrdjozn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6cmdvdWRmb2l3cnl0cmRqb3puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTQ0MjUsImV4cCI6MjA2MzU3MDQyNX0.Nu8OPqULsfZi5zHS-oEpLtRB9JPLIpWIpONOLn5puik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);